api_platform:
    title: Hello
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/Document']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
